dist: bionic

language: node_js
node_js:
  - 10.16.0

services:
  - docker

global:
  - secure: "EsUTEvs+vpeiKKcGsRjd1fLM+teIqfiwgQel1zME7VLFa25ZnX5n8KyYua30KNPqGcCnCqEQbY1dd/dfNt8tQYaiDSxDSncsWXx9HJ9e81lSzOd6kXkYwgWokm7Nj48qVFogwsPOn9ZjgXsBh8cS5Bn1QOek1qVWCiWoDHT6YGN9uNhl56cvqhF71uGDi1gDHA2EcTnMq4KnNnQ+RSnKxINC0Ot3PJuRsqFDrzecM8pLseMHQ2HxJjt49Avc1+7FdHsQyiN0K0qG7kVz+xIT52gTwhjMzHSqn5TyZbiBt+3ujY6JnIj5peOaaxTd4V4CENAseZzSB5xofeMl8VxXTWw2YoKfQ+FwyjOeMKphMYP5nrKw7N6/01CuoRmUZ6qWMHg/Ja10eYxlmLdOsgpIX7xzwS8zOKdu99ANnmq24W2fgHW5jgEBlD5zV1U0jc1hhkGmYDfzyza2M6LJY56c/qiqqo4b7x6jARBqUbu39fUzg9ypZDeA254RcCAzJvHJGnF6LSLdDL6V0ps8hObQeNaS3jpUYzf6jvMe4HeCIcal8S567IlF7mMTFZ1boRTbvBenI0BMM8C/Ol8Wsj+ukFDXLUcpKxy8o6c405Bwvx4qLBdt9VUx+6WLLNpeEwJibqrJ0Nk+/+3Gzyo/eKMJeG19qR6N/V5FdOYFx767LgQ="

branches:
  only:
  - /^v\d+\.\d+\.\d+(-\S*)?$/
  - develop

stages:
  - build docker image
  - name: deploy to dev
    if: branch = develop

jobs:
  include:
    - stage: build docker image
      script:
      - openssl aes-256-cbc -K $encrypted_54a47577e755_key -iv $encrypted_54a47577e755_iv -in gcr.json.enc -out /tmp/secrets.tar -d
      - tar xvf /tmp/secrets.tar -C /tmp/
      - cat /tmp/gcr.json | docker login -u _json_key --password-stdin https://eu.gcr.io
      - docker build -t pbb-ro --build-arg ARG_LANGUAGE={$LANGUAGE} --build-arg ARG_PBB_BOT_NAME={$PBB_BOT_NAME} --build-arg ARG_RAID_BOT_CHANNEL={$RAID_BOT_CHANNEL} --build-arg ARG_RAID_BOT_CHANNEL={$RAID_BOT_CHANNEL} --build-arg ARG_PBB_BOT_TOKEN={$PBB_BOT_TOKEN} --build-arg ARG_SHEETS_CLIENT_ID={$SHEETS_CLIENT_ID} --build-arg ARG_SHEETS_CLIENT_SECRET={$SHEETS_CLIENT_SECRET} --build-arg ARG_SHEETS_REDIRECT_URI={$SHEETS_REDIRECT_URI} --build-arg ARG_SHEETS_REFRESH_TOKEN={$SHEETS_REFRESH_TOKEN} --build-arg ARG_SHEET_API_KEY={$SHEET_API_KEY} --build-arg ARG_SHEET_ACCESS_TOKEN={$SHEET_ACCESS_TOKEN} --build-arg ARG_SHEET_ID={$SHEET_ID} --build-arg ARG_BRANCH={$TRAVIS_BRANCH} .
      - docker run pbb-ro test
      - docker tag pbb-ro eu.gcr.io/$DOCKER_USERNAME/pbb-ro:$TRAVIS_BRANCH
      - docker push eu.gcr.io/$DOCKER_USERNAME/pbb-ro:$TRAVIS_BRANCH
    - stage: deploy to dev
      script:
      - scp -i /tmp/kam-deployer.pem /tmp/gcr.json {$DEPLOY_USER}@{$DEPLOY_SERVER}:/tmp/gcr.json
      - chmod +x ./deploy.sh
      - scp -i /tmp/kam-deployer.pem deploy.sh {$DEPLOY_USER}@{$DEPLOY_SERVER}:/tmp/deploy.sh
      - chmod 600 /tmp/kam-deployer.pem && ssh -o StrictHostKeyChecking=no -i /tmp/kam-deployer.pem {$DEPLOY_USER}@{$DEPLOY_SERVER} echo $SUDO_PASSWORD | sudo -S /tmp/deploy.sh $DOCKER_USERNAME develop
