FROM node:10-alpine

ARG ARG_LANGUAGE=hu
ENV LANGUAGE=$ARG_LANGUAGE

ARG ARG_PBB_BOT_NAME="PBB Raid Organiser"
ENV PBB_BOT_NAME=$ARG_PBB_BOT_NAME
ARG ARG_RAID_BOT_CHANNEL="raid-csapatkereső"
ENV RAID_BOT_CHANNEL=$ARG_RAID_BOT_CHANNEL
ARG ARG_RAID_BOT_CHANNEL="raid-log"
ENV RAID_BOT_CHANNEL=$ARG_RAID_BOT_CHANNEL
ARG ARG_PBB_BOT_TOKEN
ENV PBB_BOT_TOKEN=$ARG_PBB_BOT_TOKEN

ARG ARG_SHEETS_CLIENT_ID
ENV SHEETS_CLIENT_ID=$ARG_SHEETS_CLIENT_ID
ARG ARG_SHEETS_CLIENT_SECRET
ENV SHEETS_CLIENT_SECRET=$ARG_SHEETS_CLIENT_SECRET
ARG ARG_SHEETS_REDIRECT_URI
ENV SHEETS_REDIRECT_URI=$ARG_SHEETS_REDIRECT_URI
ARG ARG_SHEETS_REFRESH_TOKEN
ENV SHEETS_REFRESH_TOKEN=$ARG_SHEETS_REFRESH_TOKEN
ARG ARG_SHEET_API_KEY
ENV SHEET_API_KEY=$ARG_SHEET_API_KEY
ARG ARG_SHEET_ACCESS_TOKEN
ENV SHEET_ACCESS_TOKEN=$ARG_SHEET_ACCESS_TOKEN
ARG ARG_SHEET_ID
ENV SHEET_ID=$ARG_SHEET_ID

ARG ARG_TRAVIS_BRANCH
ENV BRANCH=$ARG_TRAVIS_BRANCH

COPY ./ /usr/app

WORKDIR /usr/app

RUN mkdir -p /usr/app/logs \
    && npm install \
    && npm run build

ENTRYPOINT ["npm", "run"]

CMD ["serve"]